# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # VM1: Webserver
  config.vm.define "webserver" do |web|
    web.vm.box = "ubuntu/noble64" # Ubuntu 24.04
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    web.vm.provision "shell", path: "web_provision.sh"
  end

  # VM2: DBserver
  config.vm.define "dbserver" do |db|
    db.vm.box = "ubuntu/noble64" # Ubuntu 24.04
    db.vm.hostname = "dbserver"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "shell", path: "db_provision.sh"
  end


